2021-07-22 14:20:19,765 ERROR: Exception on / [GET][in /home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ruairi/Flask_MegaTutorial/app/main/routes.py", line 42, in index
    return render_template("index.html", title=_("Home"), form=form,
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ruairi/Flask_MegaTutorial/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/ruairi/Flask_MegaTutorial/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/ruairi/Flask_MegaTutorial/app/templates/base.html", line 48, in block 'content'
    {% block app_content %}{% endblock%}
  File "/home/ruairi/Flask_MegaTutorial/app/templates/index.html", line 11, in block 'app_content'
    {% include "_post.html"%}
  File "/home/ruairi/Flask_MegaTutorial/app/templates/_post.html", line 4, in top-level template code
    <a href="{{ url_for('user', username=post.author.username) }}">
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'main.user' instead?
2021-07-22 14:21:59,335 INFO: Microblog startup[in /home/ruairi/Flask_MegaTutorial/app/__init__.py:75]
2021-07-22 14:22:01,215 ERROR: Exception on / [GET][in /home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ruairi/Flask_MegaTutorial/app/main/routes.py", line 42, in index
    return render_template("index.html", title=_("Home"), form=form,
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ruairi/Flask_MegaTutorial/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/ruairi/Flask_MegaTutorial/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/ruairi/Flask_MegaTutorial/app/templates/base.html", line 48, in block 'content'
    {% block app_content %}{% endblock%}
  File "/home/ruairi/Flask_MegaTutorial/app/templates/index.html", line 11, in block 'app_content'
    {% include "_post.html"%}
  File "/home/ruairi/Flask_MegaTutorial/app/templates/_post.html", line 10, in top-level template code
    <a href="{{ url_for('user', username=post.author.username) }}">
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'main.user' instead?
2021-07-22 14:22:17,634 INFO: Microblog startup[in /home/ruairi/Flask_MegaTutorial/app/__init__.py:75]
2021-07-22 14:22:31,108 ERROR: Exception on /user/Rarf [GET][in /home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ruairi/Flask_MegaTutorial/app/main/routes.py", line 53, in user
    page, app.config["POSTS_PER_PAGE"], False)
NameError: name 'app' is not defined
2021-07-22 14:22:51,043 INFO: Microblog startup[in /home/ruairi/Flask_MegaTutorial/app/__init__.py:75]
