2021-07-22 12:57:41,182 INFO: Microblog startup[in /home/ruairi/Flask_MegaTutorial/app/__init__.py:75]
2021-07-22 12:57:43,102 ERROR: Exception on / [GET][in /home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
  File "/home/ruairi/Flask_MegaTutorial/app/main/routes.py", line 18, in before_request
    g.locale = str(get_locale())
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_babel/__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
  File "/home/ruairi/Flask_MegaTutorial/app/__init__.py", line 82, in get_locale
    return request.accept_languages.best_match(app.config["LANGUAGES"])
NameError: name 'app' is not defined
2021-07-22 12:57:43,615 ERROR: Exception on /favicon.ico [GET][in /home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1489, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1471, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/ctx.py", line 367, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2032, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1383, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1323, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/ruairi/Flask_MegaTutorial/app/errors/handlers.py", line 7, in not_found_error
    return render_template("errors/404.html"), 404
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ruairi/Flask_MegaTutorial/app/templates/errors/404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ruairi/Flask_MegaTutorial/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 26, in block 'body'
    {% block scripts %}
  File "/home/ruairi/Flask_MegaTutorial/app/templates/base.html", line 66, in block 'scripts'
    $(destElem).text("{{ _('Error: Could not contact server.') }}");
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/jinja2/ext.py", line 168, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/jinja2/ext.py", line 174, in gettext
    rv = __context.call(func, __string)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_babel/__init__.py", line 109, in <lambda>
    lambda x: get_translations().ugettext(x),
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_babel/__init__.py", line 209, in get_translations
    return get_domain().get_translations()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_babel/__init__.py", line 554, in get_translations
    locale = get_locale()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask_babel/__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
  File "/home/ruairi/Flask_MegaTutorial/app/__init__.py", line 82, in get_locale
    return request.accept_languages.best_match(app.config["LANGUAGES"])
NameError: name 'app' is not defined
2021-07-22 12:59:04,568 INFO: Microblog startup[in /home/ruairi/Flask_MegaTutorial/app/__init__.py:75]
2021-07-22 12:59:12,941 INFO: Microblog startup[in /home/ruairi/Flask_MegaTutorial/app/__init__.py:75]
2021-07-22 12:59:26,087 INFO: Microblog startup[in /home/ruairi/Flask_MegaTutorial/app/__init__.py:75]
2021-07-22 12:59:28,360 ERROR: Exception on /auth/login [GET][in /home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ruairi/Flask_MegaTutorial/app/auth/routes.py", line 29, in login
    return render_template("login.html", title=_("Sign In"), form=form)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ruairi/Flask_MegaTutorial/venv/lib/python3.8/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
2021-07-22 13:07:34,595 INFO: Microblog startup[in /home/ruairi/Flask_MegaTutorial/app/__init__.py:75]
